### PR TITLE
Wrap node name in `\tikz@pp@name` when passed to pgf gd

### LINKED ISSUE #1087: Graph drawing doesn't work with `name prefix`
**Brief outline of the bug**

When `name prefix` (or `name suffix`) is set, graph drawing throws Lua error
```tex
...graphdrawing/lua/pgf/gd/interface/InterfaceToDisplay.lua:510: attempting to create edge between nodes c and a that are not in the graph
stack traceback:
	[C]: in function 'assert'
	...graphdrawing/lua/pgf/gd/interface/InterfaceToDisplay.lua:510: in function 'pgf.gd.interface.InterfaceToDisplay.createEdge'
	[\directlua]:1: in main chunk.
\pgfgdedge ...uaescapestring {\the \toks 1}', }) }
                                                  \endpgfinterruptpath }}\en...
```

**Minimal working example (MWE)**

```latex
% !TeX program = lualatex
\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{graphs, graphdrawing}
\usegdlibrary{layered}

\begin{document}
% without graphdrawing
\tikz                \graph { {a,b} -> c }; % works
\tikz[name prefix=x] \graph { {a,b} -> c }; % works

% with graphdrawing
\tikz                \graph[layered layout] { {a,b} -> c }; % works
\tikz[name prefix=x] \graph[layered layout] { {a,b} -> c }; % lua error
\tikz[name prefix=x] \graph[layered layout, /tikz/name prefix=]
                       { {a,b} -> c };                      % works again
\end{document}
```

I don't speak Lua, but by adding `print()` to function `InterfaceToDisplay.createEdge()`, I find when the error is thrown,
see lines 482--484 below, `head == 'c'` and `tail == 'a'`. However the keys stored in table `scope.node_names` is `xa, xb, xc`. Hence both `h` and `t` are nil and the `assert()` fails.

https://github.com/pgf-tikz/pgf/blob/247f1f0445a9e996560c9f5a9b3fb03a4184e6ec/tex/generic/pgf/graphdrawing/lua/pgf/gd/interface/InterfaceToDisplay.lua#L475-L495

### PR DESCRIPTION
**Pull request by muzimuzhi**
**Motivation for this change**

This PR consists of several parts, all `gd` related:
 - a fix for #1087
 - a new test set for `gd` which only runs on LuaTeX and may overlap with (final development of) #1116
 - a test case which aims to check only the just fixed problem, not the whole `gd`

To me, checking internal states and more human-readable generated log lines (here `.tlg`) is preferable to seeing lengthy box content, so I introduce the `pgfgd-debug.lua` which adds debugging code to Lua functions in `InterfaceToDisplay`.

Todo or possible improvements:
 - Fully expand `\tikz@pp@name{<node name>}` before being passed to macros. Again a call for pgf's `\exp_args:Nx` and `\exp_args:Nxx`.
 - In `pgfgd-regression-test.tex`, how to input `pgf-regression-test.tex` which resides in `support` sub-directory of another test set?
 - Allow test files selectively turning on/off wrappers in `pgfgd-debug.lua`. Can be achieved with some higher-order functions written in Lua, is it?

Fixes #1087

**Checklist**

Please [signoff your commits][git-s] to explicitly state your agreement to the [Developer Certificate of Origin][DCO]. If that is not possible you may check the boxes below instead:

- [x] Code changes are licensed under [GPLv2][GPL] + [LPPLv1.3c][LPPL]
- [x] Documentation changes are licensed under [FDLv1.2][FDL]

[git-s]: https://git-scm.com/docs/git-commit#Documentation/git-commit.txt--s
[DCO]: https://developercertificate.org
[GPL]: https://www.gnu.org/licenses/gpl-2.0.html
[LPPL]: https://www.latex-project.org/lppl/lppl-1-3c.txt
[FDL]: https://www.gnu.org/licenses/fdl-1.2.html

### CODE REVIEW

**Comment by muzimuzhi** [comment]
> * Allow test files selectively turning on/off wrappers in `pgfgd-debug.lua`. Can be achieved with some higher-order functions written in Lua, is it?

`\luafunction` fits here. I got to know it from https://github.com/latex3/latex2e/pull/536.

File: testfiles-gd/support/pgfgd-debug.lua [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+function InterfaceToDisplay.addToVertexOptions(...)
+  local name = ...
+  debug("Add options to vertex '%s'", name)
+  addToVertexOptions(...)
+end
+
+
+-- helper
+function debug(format_str, ...)
+  tex.sprint(string.format("\\pgfgdluainfo{" .. format_str .. "}", ...))
```
Comment (hmenke) [inline testfiles-gd/support/pgfgd-debug.lua]: Maybe `texio.write_nl` to write to the log directly? Or you can use my complicated solution here to use `\message` at the correct point: https://tex.stackexchange.com/questions/470621/how-to-emulate-message-in-luatex

File: testfiles-gd/support/pgfgd-debug.lua [hunk 2]
```diff
@@ -0,0 +1,39 @@
...
+local addToVertexOptions = InterfaceToDisplay.addToVertexOptions
+function InterfaceToDisplay.addToVertexOptions(...)
+  local name = ...
+  debug("Add options to vertex '%s'", name)
+  addToVertexOptions(...)
+end
+
+
+-- helper
+function debug(format_str, ...)
```
Comment (hmenke) [inline testfiles-gd/support/pgfgd-debug.lua]: This is really bad, sorry. It shadows Lua's builtin [`debug` library](https://www.lua.org/manual/5.4/manual.html#6.10).

Comment (muzimuzhi) [reply testfiles-gd/support/pgfgd-debug.lua]: Sorry I know nothing about lua's stdlib (and very very little to lua itself). Maybe `Pgfgd.debug` or do you have any suggested name?

File: testfiles-gd/support/pgfgd-debug.lua (hunk 1 above)
Comment (muzimuzhi) [reply testfiles-gd/support/pgfgd-debug.lua]: I will try to learn and understand your answer there. If not succeed, I will choose the simpler `texio.write_nl` cause in my very limited knowledge (and an amateur's feeling) to lua and pgf's `graphdrawing`, writing to log "at the correct point" is not so significant here.

**Comment by hmenke** [comment]
Sorry, now I broke the tests. I'll look in the evening at home why that happens.

File: testfiles-gd/support/pgfgd-regression-test.tex [hunk 3]
```diff
@@ -1,18 +1,5 @@
 \input regression-test.tex
 
-\catcode`\@=11 % \makeatletter
-
-% this macro should be used _after_ graphdrawing library is loaded
-\def\pgfgdBeforeBeginDocument{
-  % redirect error
-  \def\pgfutil@packageerror#1#2#3{\immediate\write17{Package #1 Error: #2.}}
```
Comment (muzimuzhi) [inline testfiles-gd/support/pgfgd-regression-test.tex]: @hmenke It's the removal of this line that broken the test. The aim was to test that specific usage does throw errors. 

hmm it only takes responsibility of the "error" part.

File: testfiles-gd/support/pgfgd-regression-test.tex [hunk 4]
```diff
@@ -1,18 +1,5 @@
 \input regression-test.tex
 
-\catcode`\@=11 % \makeatletter
-
-% this macro should be used _after_ graphdrawing library is loaded
-\def\pgfgdBeforeBeginDocument{
```
Comment (muzimuzhi) [inline testfiles-gd/support/pgfgd-regression-test.tex]: Now the test fails with
```
pgfgd-debug.lua:1: attempt to index a nil value (global 'pgf')
```
because when `pgfgd-debug.lua` is read in, the whole `pgf` is not loaded yet. This explains why the `\pgfgdBeforeBeginDocument` was introduced (and used after package loading and just before `\begin{document}`). For latex format only, `\AtBeginDocument` suffices but I more or less want(ed) a portable solution (not a strong opinion).

**Comment by muzimuzhi** [comment]
Now "Test suite" is successful. "Check commits" still fails because of https://github.com/pgf-tikz/pgf/pull/1119/commits/b65622a44ceda8201019271f2d311b7c45725c21 I made on webpage to resolve merge conflicts.

A reminder: Now `*.diff` files, if exist, from both test sets are uploaded in a flattened structure. It would be more helpful if the corresponding `.log` files are uploaded too.

Oh this is already merged, so any "refactoring welcome" words is less useable.
